---

- import_tasks: conf.yml
  tags:
    - configure
    - awslogs

- import_tasks: install.yml
  tags:
    - install
    - awslogs

- import_tasks: start.yml
  tags:
    - start
    - restart
    - service
    - awslogs

- import_tasks: cleanup.yml
  tags:
    - cleanup
    - awslogs
